<?php

namespace Database\Seeders;

use App\Models\Area;
use Illuminate\Database\Seeder;

class AreaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $areas = [
            ['id' => '1', 'name_ar' => 'جابر الاحمد', 'name_en' => 'Jaber Al Ahmad', 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => '2', 'name_ar' => 'صباح الاحمد', 'name_en' => 'Sabah Al Ahmad', 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => '3', 'name_ar' => 'صباح الناصر', 'name_en' => 'Sabah Al-Naser', 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => '4', 'name_ar' => 'الفنيطيس', 'name_en' => 'Funaitees', 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => '5', 'name_ar' => 'القصر', 'name_en' => 'Qasar', 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => '6', 'name_ar' => 'الرقة', 'name_en' => 'Riqaa', 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => '7', 'name_ar' => 'الفردوس', 'name_en' => 'Firdous', 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => '8', 'name_ar' => 'النعيم', 'name_en' => 'Naeem', 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => '9', 'name_ar' => 'شمال غرب الاحمدي', 'name_en' => 'North West Sulaibikh', 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => '10', 'name_ar' => 'الصليبخات', 'name_en' => 'Sulaibikhaat', 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => '11', 'name_ar' => 'سعد العبد الله', 'name_en' => 'Saad Al Abdallah', 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => '12', 'name_ar' => 'القادسية', 'name_en' => 'Qadsiya', 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => '13', 'name_ar' => 'اشبيلية', 'name_en' => 'Ishbliya', 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => '14', 'name_ar' => 'العيون', 'name_en' => 'Oyoun', 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => '15', 'name_ar' => 'مشرف', 'name_en' => 'Mishrif', 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => '16', 'name_ar' => 'النسيم', 'name_en' => 'Naseem', 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => '17', 'name_ar' => 'مبارك الكبير', 'name_en' => 'Mubarak Al-Kabeer', 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => '18', 'name_ar' => 'الشدادية', 'name_en' => 'Shuhadaa', 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => '19', 'name_ar' => 'الفروانية', 'name_en' => 'Farwaniya', 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => '20', 'name_ar' => 'الصليبية', 'name_en' => 'Sulaibiya', 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => '21', 'name_ar' => 'تيماء', 'name_en' => 'Taima', 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => '22', 'name_ar' => 'السرة', 'name_en' => 'Surra', 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => '23', 'name_ar' => 'العارضية', 'name_en' => 'Ardiya', 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => '24', 'name_ar' => 'السالمية', 'name_en' => 'Salmyia', 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => '25', 'name_ar' => 'ابو فطير', 'name_en' => 'Abu Fatera', 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => '26', 'name_ar' => 'غرب عبد الله المبارك', 'name_en' => 'West Abdullah Al Mubarak', 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => '27', 'name_ar' => 'اليرموك', 'name_en' => 'Yarmouk', 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => '28', 'name_ar' => 'الرحاب', 'name_en' => 'Rehab', 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => '29', 'name_ar' => 'بيان', 'name_en' => 'Bayan', 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => '30', 'name_ar' => 'المنقف', 'name_en' => 'Mangaf', 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => '31', 'name_ar' => 'القصور', 'name_en' => 'Qusoor', 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => '32', 'name_ar' => 'السلام', 'name_en' => 'Salam', 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => '33', 'name_ar' => 'فهد الاحمد', 'name_en' => 'Fahd Al Ahmad', 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => '34', 'name_ar' => 'الرميثية', 'name_en' => 'Rumaithiya', 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => '35', 'name_ar' => 'عبد الله المبارك', 'name_en' => 'Abdullah Mubarak', 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => '36', 'name_ar' => 'الجهراء', 'name_en' => 'Jahra', 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => '37', 'name_ar' => 'الزهراء', 'name_en' => 'Zahra', 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => '38', 'name_ar' => 'ام الهيمان', 'name_en' => 'Oum Al Himan', 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => '39', 'name_ar' => 'الصباحية', 'name_en' => 'Sabahiya', 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => '40', 'name_ar' => 'العدان', 'name_en' => 'Adan', 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => '41', 'name_ar' => 'الدوحة', 'name_en' => 'Doha', 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => '42', 'name_ar' => 'صباح السالم', 'name_en' => 'Sabah Al-Salem', 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => '43', 'name_ar' => 'المهبولة', 'name_en' => 'Mahboola', 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => '44', 'name_ar' => 'جليب الشيوخ', 'name_en' => 'Jaleeb Shuwyukh', 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => '45', 'name_ar' => 'غرناطة', 'name_en' => 'Gharnata', 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => '46', 'name_ar' => 'الضهر', 'name_en' => 'Dhahar', 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => '47', 'name_ar' => 'القيروان', 'name_en' => 'Qairawan', 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => '48', 'name_ar' => 'خيطان', 'name_en' => 'Khaitan', 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => '49', 'name_ar' => 'قرطبة', 'name_en' => 'Qortuba', 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => '50', 'name_ar' => 'النهضة', 'name_en' => 'Al-Nahda', 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => '51', 'name_ar' => 'حطين', 'name_en' => 'Hitteen', 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => '52', 'name_ar' => 'الجابرية', 'name_en' => 'Jabriya', 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => '53', 'name_ar' => 'هدية', 'name_en' => 'Hadiya', 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => '54', 'name_ar' => 'العمرية', 'name_en' => 'Omariya', 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => '55', 'name_ar' => 'الفحيحيل', 'name_en' => 'Fahaheel', 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => '56', 'name_ar' => 'حولي', 'name_en' => 'Hawalli', 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => '57', 'name_ar' => 'الصديق', 'name_en' => 'Siddiq', 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => '58', 'name_ar' => 'العقيلة', 'name_en' => 'Aqaela', 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => '59', 'name_ar' => 'الروضة', 'name_en' => 'Rawda', 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => '60', 'name_ar' => 'الرقعي', 'name_en' => 'Rigai', 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => '61', 'name_ar' => 'الوفرة', 'name_en' => 'Wafra', 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => '62', 'name_ar' => 'الاندلس', 'name_en' => 'Andalous', 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => '63', 'name_ar' => 'الرابية', 'name_en' => 'Rabiya', 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => '64', 'name_ar' => 'ابو الحصانية', 'name_en' => 'Abu Hasaniya', 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => '65', 'name_ar' => 'ابو حليفة', 'name_en' => 'Abu Halifa', 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => '66', 'name_ar' => 'الدعية', 'name_en' => 'Daiya', 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => '67', 'name_ar' => 'خيران', 'name_en' => 'Kheiran', 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => '68', 'name_ar' => 'المسايل', 'name_en' => 'Masayel', 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => '69', 'name_ar' => 'الأحمدي', 'name_en' => 'Ahmadi', 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => '70', 'name_ar' => 'عبد الله السالم', 'name_en' => 'Abdulla Al Salem', 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => '71', 'name_ar' => 'العديلية', 'name_en' => 'Adailiya', 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => '72', 'name_ar' => 'الواحة', 'name_en' => 'Waha', 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => '73', 'name_ar' => 'الفيحاء', 'name_en' => 'Faiha', 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => '74', 'name_ar' => 'الدسمة', 'name_en' => 'Dasma', 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => '75', 'name_ar' => 'مبارك العبد الله', 'name_en' => 'Mubarak Al Abdulla A', 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => '76', 'name_ar' => 'بنيد القار', 'name_en' => 'Bnaid Al-Qar', 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => '77', 'name_ar' => 'مدينة الكويت', 'name_en' => 'Kuwait City', 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => '78', 'name_ar' => 'سلوى', 'name_en' => 'Salwa', 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => '79', 'name_ar' => 'القرين', 'name_en' => 'Qurain', 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => '80', 'name_ar' => 'جابر العلي', 'name_en' => 'Jaber Al-Ali', 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => '81', 'name_ar' => 'كيفان', 'name_en' => 'Kifan', 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => '82', 'name_ar' => 'الفنطاس', 'name_en' => 'Fintas', 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => '83', 'name_ar' => 'كبد', 'name_en' => 'Kabed', 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => '84', 'name_ar' => 'المسيلة', 'name_en' => 'Maseela', 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => '85', 'name_ar' => 'الخالدية', 'name_en' => 'Khaldiya', 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => '86', 'name_ar' => 'الشعب', 'name_en' => 'Shaab', 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => '87', 'name_ar' => 'المنصورية', 'name_en' => 'Mansouriya', 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => '88', 'name_ar' => 'الري', 'name_en' => 'Rai', 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => '89', 'name_ar' => 'الشامية', 'name_en' => 'Shamiya', 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => '90', 'name_ar' => 'الضجيج', 'name_en' => 'Dajeej', 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => '91', 'name_ar' => 'العارضية الحرفية', 'name_en' => 'Ardiya Herafi', 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => '92', 'name_ar' => 'الضباعية', 'name_en' => 'Al-Dhebaiyah', 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => '93', 'name_ar' => 'الشويخ السكنية', 'name_en' => 'Shuwaikh (Residential)', 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => '94', 'name_ar' => 'العبدلي', 'name_en' => 'Abdali', 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => '95', 'name_ar' => 'ميدان حولي', 'name_en' => 'Hawally Square', 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => '96', 'name_ar' => 'النزهة', 'name_en' => 'Nuzha', 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => '97', 'name_ar' => 'جنوب الجهراء', 'name_en' => 'South Jahra', 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => '98', 'name_ar' => 'جنوب الاحمدي', 'name_en' => 'South Ahmadi', 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => '99', 'name_ar' => 'العباسية', 'name_en' => 'Abbasiya', 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => '100', 'name_ar' => 'شرق', 'name_en' => 'Sharq', 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => '101', 'name_ar' => 'شمال الاحمدي', 'name_en' => 'North Ahmadi', 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => '102', 'name_ar' => 'امغرة', 'name_en' => 'Amghra', 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => '103', 'name_ar' => 'صبحان', 'name_en' => 'Subhan', 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => '104', 'name_ar' => 'الجليعة', 'name_en' => 'Julaia', 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
            ['id' => '105', 'name_ar' => 'بنيدر', 'name_en' => 'Benaider', 'created_at' => null, 'updated_at' => null, 'deleted_at' => null],
        ];

        Area::insert($areas);
    }
}
